name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish-msi:
    name: Publish MSI to WinGet
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: zed.rainxch.githubstore
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}

  publish-exe:
    name: Publish EXE to WinGet
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: zed.rainxch.githubstore
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}